// <auto-generated />
using System;
using InvoiceManage.Database.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace InvoiceManage.Database.Migrations
{
    [DbContext(typeof(SqliteDbContext))]
    [Migration("20240103205152_Init")]
    partial class Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.17");

            modelBuilder.Entity("InvoiceManage.Database.Entities.Company", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BaseUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClientId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Crn")
                        .HasColumnType("TEXT");

                    b.Property<string>("FilePath")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Pro")
                        .HasColumnType("TEXT");

                    b.Property<string>("Sbc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Scln")
                        .HasColumnType("TEXT");

                    b.Property<string>("Tins")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Company");
                });

            modelBuilder.Entity("InvoiceManage.Database.Entities.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long?>("BId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Bbc")
                        .HasColumnType("TEXT");

                    b.Property<string>("BillId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Bpc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Bpn")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Pro")
                        .HasColumnType("TEXT");

                    b.Property<string>("Tinb")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Customer");
                });

            modelBuilder.Entity("InvoiceManage.Database.Entities.Invoice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Acn")
                        .HasColumnType("TEXT");

                    b.Property<string>("Bbc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Bid")
                        .HasColumnType("TEXT");

                    b.Property<string>("BillId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Bpc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Bpn")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Cap")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Cdcd")
                        .HasColumnType("TEXT");

                    b.Property<string>("Cdcd_1")
                        .HasColumnType("TEXT");

                    b.Property<string>("Cdcn")
                        .HasColumnType("TEXT");

                    b.Property<long>("CompanyId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CompanyId1")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Crn")
                        .HasColumnType("TEXT");

                    b.Property<int>("Ft")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("GenerateInno")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Iinn")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Indatim")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Indatim2m")
                        .HasColumnType("TEXT");

                    b.Property<string>("Indatim2m_1")
                        .HasColumnType("TEXT");

                    b.Property<string>("Indatim2m_2")
                        .HasColumnType("TEXT");

                    b.Property<string>("Indatim_1")
                        .HasColumnType("TEXT");

                    b.Property<string>("Indatim_2")
                        .HasColumnType("TEXT");

                    b.Property<string>("Inno")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Inno_1")
                        .HasColumnType("TEXT");

                    b.Property<int>("Inp")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Ins")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Insp")
                        .HasColumnType("TEXT");

                    b.Property<int>("Inty")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Inty_1")
                        .HasColumnType("TEXT");

                    b.Property<string>("Irtaxid")
                        .HasColumnType("TEXT");

                    b.Property<string>("Pcn")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Pdt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Pdt_1")
                        .HasColumnType("TEXT");

                    b.Property<string>("Pdt_2")
                        .HasColumnType("TEXT");

                    b.Property<string>("Pid")
                        .HasColumnType("TEXT");

                    b.Property<int>("Pmt")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Pv")
                        .HasColumnType("TEXT");

                    b.Property<string>("RefrenceNumber")
                        .HasColumnType("TEXT");

                    b.Property<string>("ResultStatus")
                        .HasColumnType("TEXT");

                    b.Property<string>("Sbc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Scc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Scln")
                        .HasColumnType("TEXT");

                    b.Property<string>("SendStatus")
                        .HasColumnType("TEXT");

                    b.Property<int>("Setm")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Tadis")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Tax17")
                        .HasColumnType("TEXT");

                    b.Property<string>("TaxId")
                        .HasMaxLength(22)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Tbill")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Tdis")
                        .HasColumnType("TEXT");

                    b.Property<string>("Tinb")
                        .HasColumnType("TEXT");

                    b.Property<string>("Tins")
                        .HasColumnType("TEXT");

                    b.Property<string>("Tm")
                        .HasColumnType("TEXT");

                    b.Property<int>("Tob")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Tocv")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Todam")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Tonw")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Torv")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Tprdis")
                        .HasColumnType("TEXT");

                    b.Property<string>("Trmn")
                        .HasColumnType("TEXT");

                    b.Property<string>("Trn")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Tvam")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Tvop")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId1");

                    b.ToTable("Invoice");
                });

            modelBuilder.Entity("InvoiceManage.Database.Entities.InvoiceItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Adis")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Am")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Bros")
                        .HasColumnType("TEXT");

                    b.Property<string>("Bsrn")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("CFee")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Consfee")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Cop")
                        .HasColumnType("TEXT");

                    b.Property<string>("Cut")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Dis")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Exr")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Fee")
                        .HasColumnType("TEXT");

                    b.Property<long>("InvoiceId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("InvoiceId1")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Mu")
                        .HasColumnType("TEXT");

                    b.Property<string>("Mu_1")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Nw")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Odam")
                        .HasColumnType("TEXT");

                    b.Property<double>("Odr")
                        .HasColumnType("REAL");

                    b.Property<string>("Odt")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Olam")
                        .HasColumnType("TEXT");

                    b.Property<double>("Olr")
                        .HasColumnType("REAL");

                    b.Property<string>("Olt")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Prdis")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Pspd")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Spro")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Sscv")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Ssrv")
                        .HasColumnType("TEXT");

                    b.Property<string>("SstId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Sstt")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Tcpbs")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Tsstam")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Vam")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Vop")
                        .HasColumnType("TEXT");

                    b.Property<double>("Vra")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("InvoiceId1");

                    b.ToTable("InvoiceItem");
                });

            modelBuilder.Entity("InvoiceManage.Database.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("InternalCode")
                        .HasColumnType("TEXT");

                    b.Property<string>("Sstid")
                        .HasColumnType("TEXT");

                    b.Property<string>("Sstt")
                        .HasColumnType("TEXT");

                    b.Property<double>("Vra")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("Product");
                });

            modelBuilder.Entity("InvoiceManage.Database.Entities.Invoice", b =>
                {
                    b.HasOne("InvoiceManage.Database.Entities.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId1");

                    b.Navigation("Company");
                });

            modelBuilder.Entity("InvoiceManage.Database.Entities.InvoiceItem", b =>
                {
                    b.HasOne("InvoiceManage.Database.Entities.Invoice", "Invoice")
                        .WithMany("Items")
                        .HasForeignKey("InvoiceId1");

                    b.Navigation("Invoice");
                });

            modelBuilder.Entity("InvoiceManage.Database.Entities.Invoice", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
